stages:
  - Deploy-Build
  - sonar 

variables:
  TRIGRAM: "DEM"

include:
  - project: 'common/ci-chain'
    file:
      - build.yml
    ref: V1
  - project: common/sonar-scan
    ref: V1
    file: sonar.yml

build:
  extends: .main
  stage: Deploy-Build
  variables:
    IMAGE_VERSION: "0.0.1"
    IMAGE_NAME: demo-books-nhajji
    HARBOR_REPO: issc-dem
